default_stages: [commit, push]
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    - id: black
      args: [
        --line-length=88, 
        src/
      ]
      exclude: ^(tools/|docs/)
      types: ['python']
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.2
    hooks:
    - id: flake8
      args: [
        --max-line-length=88,
        src/
      ]
      exclude: ^(tools/|docs/)
      types: ['python']